# Generated by Django 4.2 on 2023-04-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Date_Of_Birth', models.IntegerField()),
                ('Gender', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
