# Generated by Django 4.2 on 2023-05-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_app', '0002_alter_info_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Age',
        ),
    ]
